#!/bin/bash

#######################################################################
# Copyright © 2015 The CoDoLa developer team
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#######################################################################

BASEDIR=$(dirname $0)
cd $2
PDFLATEX="$BASEDIR/$1/bin/x86_64-linux/pdflatex"
FILE="$2/$3"
LOG_FILE="$FILE.out.log"
echo "Executing PDFLatex ($PDFLATEX) for file $FILE"
NO_FILES=9999

runPdfLatex(){

	"$PDFLATEX" -interaction=nonstopmode "$FILE" > "$LOG_FILE";
	cat "$LOG_FILE"
	NEW_NO_FILES=`cat "$LOG_FILE" | grep "No file" | wc -l`;
	if [ ${NEW_NO_FILES} < ${NO_FILES} ]; then
		NO_FILES=${NEW_NO_FILES}
		runPdfLatex
	else
		echo "Done"
	fi
}

runPdfLatex
